[package]
name = "gs_client"
version = "0.0.0"
description = "Geosia client"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

default-run = "gs_client"

[lints]
workspace = true

[dependencies]
# Local
gs_schemas.workspace = true
gs_common.workspace = true
# Remote
anyhow.workspace = true
capnp.workspace = true
hashbrown.workspace = true
image.workspace = true
quinn.workspace = true
slotmap.workspace = true
smallvec.workspace = true
socket2.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing.workspace = true
# Remote, bevy plugins
bevy_egui.workspace = true
uuid = { version = "1.23.4", features = ["v4"] }

[dependencies.bevy]
workspace = true
features = [
    # Default Bevy functionality:
    "2d",
    "3d",
    "ui"
]

[features]
trace_tracy = ["gs_common/trace_tracy", "bevy/trace_tracy"]
