[package]
name = "gs_schemas"
version = "0.0.1"
description = "Disk and network data serialization schemas for the Geosia game"

authors.workspace = true
rust-version.workspace = true
license.workspace = true
edition.workspace = true
repository = "https://github.com/GeosiaGame/Geosia/tree/dev/lib/gs_schemas"

[lints]
workspace = true

[features]
default = []
regenerate-capnp = []

[[bench]]
name = "schemabench"
harness = false

[dependencies]
anyhow.workspace = true
bytemuck.workspace = true
bytes.workspace = true
bitflags.workspace = true
bitvec.workspace = true
bevy_math.workspace = true
bevy_color.workspace = true
bevy_reflect.workspace = true
capnp.workspace = true
chrono.workspace = true
either.workspace = true
futures.workspace = true
hashbrown.workspace = true
itertools.workspace = true
kstring.workspace = true
serde.workspace = true
smallvec.workspace = true
thiserror.workspace = true
uuid.workspace = true
rand.workspace = true
rand_xoshiro.workspace = true
rusqlite.workspace = true
noise.workspace = true
zorder.workspace = true
zstd.workspace = true

[dev-dependencies]
criterion.workspace = true
rand.workspace = true
rand_pcg.workspace = true
tempfile.workspace = true
quickcheck.workspace = true
quickcheck_macros.workspace = true

[build-dependencies]
build-rs.workspace = true
capnpc.workspace = true
rusqlite.workspace = true
zstd.workspace = true
