use core::cell::RefCell;
use std::hash::Hash;
use hashbrown::HashMap;
use noise::NoiseFn;

/// Noise function that caches the last output value generated by the source
/// function.
///
/// If the input coordinates passed to `Cache::get` are equal to the previous
/// call, the function returns the cached result of the previous call to
/// `Source::get`. Otherwise, `Source::get` is called with the new coordinates,
/// overwriting the cache with the result, and returning the result to the
/// caller.
///
/// Caching a noise function is useful if it is used as a source function for
/// multiple noise functions. If a source function is not cached, the source
/// function will redundantly calculate the same output value once for each
/// noise function in which it is included.
#[derive(Clone, Debug)]
pub struct Cache<T, Source, const DIM: usize> {
    /// Outputs the value to be cached.
    pub source: Source,

    cache: RefCell<HashMap<[T; DIM], f64>>,
}

impl<T, Source, const DIM: usize> Cache<T, Source, DIM> {
    pub fn new(source: Source) -> Self {
        Cache {
            source,
            cache: RefCell::new(HashMap::new()),
        }
    }
}

impl<T, Source, const DIM: usize> NoiseFn<T, DIM> for Cache<T, Source, DIM>
where
    T: Copy + Hash + Eq,
    Source: NoiseFn<T, DIM>,
{
    fn get(&self, point: [T; DIM]) -> f64 {
        if let Some(&value) = self.cache.borrow().get(&point) {
            value
        } else {
            let value = self.source.get(point);
            self.cache.borrow_mut().insert(point, value);
            value
        }
    }
}

fn quick_eq(a: &[f64], b: &[f64]) -> bool {
    assert_eq!(a.len(), b.len());

    a.iter().eq(b)
}
