use std::hash::Hash;
use std::sync::Arc;
use hashbrown::HashMap;
use noise::NoiseFn;

/// Noise function that caches previous output values generated by the source function.
///
/// Caching a noise function is useful if it is used as a source function for multiple noise functions. If a source
/// function is not cached, the source function will redundantly calculate the same output value once for each noise
/// function in which it is included.
#[derive(Debug)]
pub struct Cache<T, Source, const DIM: usize> {
    /// Outputs the value to be cached.
    pub source: Source,

    cache: Arc<HashMap<[T; DIM], f64>>,
}

impl<T, Source, const DIM: usize> Cache<T, Source, DIM> {
    pub fn new(source: Source) -> Self {
        Cache {
            source,
            cache: Arc::new(HashMap::new()),
        }
    }
}

impl<T, Source, const DIM: usize> NoiseFn<T, DIM> for Cache<T, Source, DIM>
where
    T: Copy + Hash + Eq,
    Source: NoiseFn<T, DIM>,
{
    fn get(&self, point: [T; DIM]) -> f64 {
        if let Some(&value) = self.cache.get(&point) {
            value
        } else {
            let value = self.source.get(point);
            let mut map = Arc::clone(&self.cache);
            Arc::get_mut(&mut map).unwrap().insert(point, value);
            value
        }
    }
}
