on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - dev
  workflow_dispatch:

name: Check PR

concurrency:
  cancel-in-progress: true
  group: pr/${{ github.ref }}

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  tests:
    name: ${{ matrix.rust }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04 ]
        rust: [ '1.86.0', nightly-2025-05-03 ]
        include:
          - os: ubuntu-24.04
#          - os: macos-latest
    env:
      RUST_BACKTRACE: full
      RUSTV: ${{ matrix.rust }}
    steps:
      - name: Install dependencies
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get update --yes
          sudo apt-get install --yes --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev libvulkan-dev
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-r${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
      - name: Install Rust ${{ matrix.rust }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Run tests
        run: cargo "+${{ matrix.rust }}" test --workspace
      - name: Clippy
        run: cargo "+${{ matrix.rust }}" clippy --all-targets -- -D warnings
      - name: Clippy - Server-only build
        run: cargo "+${{ matrix.rust }}" clippy -p gs_common -- -D warnings
      - name: Clippy - Schemas-only build
        run: cargo "+${{ matrix.rust }}" clippy -p gs_schemas -- -D warnings
      - name: Check formatting
        if: startsWith(matrix.rust, 'nightly')
        run: cargo "+${{ matrix.rust }}" fmt --check --all

